# Generated by Django 5.2.16 on 2026-09-19 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def merge_game_states(apps, schema_editor):
    for name in ("Game", "HistoricalGame"):
        model = apps.get_model("app", name)
        for old, new in (("Completed", "Played"), ("Paused", "Played"), ("Planning", "Planned")):
            model.objects.using(schema_editor.connection.alias).filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_restore_tz_shifted_media_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(null=True)),
                ('attempted_at', models.DateTimeField(null=True)),
                ('error', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Played', 'Played'), ('In progress', 'In Progress'), ('Dropped', 'Dropped')], default='Planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Played', 'Played'), ('In progress', 'In Progress'), ('Dropped', 'Dropped')], default='Planned', max_length=20),
        ),
        migrations.RunPython(merge_game_states),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Planned', 'Played', 'In progress', 'Dropped'])), name='game_status_allowed'),
        ),
        migrations.AddField(
            model_name='collectionfacts',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_facts', to='app.item'),
        ),
    ]
