# Generated by Django 5.2.16 on 2026-09-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_collectionfacts_alter_game_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=500)),
                ('aliases', models.JSONField(default=list)),
                ('search_text', models.TextField()),
                ('image', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('adult', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'kind'], name='discovery_source_kind')],
                'constraints': [models.UniqueConstraint(fields=('source', 'kind', 'external_id'), name='discovery_identity_unique')],
            },
        ),
    ]
