# Generated by Django 5.2.16 on 2026-09-20 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_discovery_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='game_status_allowed',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Owned', 'Owned'), ('Planned', 'Planned'), ('Played', 'Played'), ('In progress', 'In Progress'), ('Dropped', 'Dropped')], default='Planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='status',
            field=models.CharField(choices=[('Owned', 'Owned'), ('Planned', 'Planned'), ('Played', 'Played'), ('In progress', 'In Progress'), ('Dropped', 'Dropped')], default='Planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmovie',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Owned', 'Owned'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Owned', 'Owned'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Owned', 'Planned', 'Played', 'In progress', 'Dropped'])), name='game_status_allowed'),
        ),
    ]
