# Generated by Django 5.2.16 on 2026-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_owned_status_and_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryentry',
            name='prominence',
            field=models.FloatField(default=0),
        ),
    ]
