# Generated by Django 5.2.16 on 2026-09-19 23:30

from django.db import migrations, models


def merge_game_filters(apps, schema_editor):
    model = apps.get_model("users", "User")
    for old, new in (("Completed", "Played"), ("Paused", "Played"), ("Planning", "Planned")):
        model.objects.using(schema_editor.connection.alias).filter(game_status=old).update(game_status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_collectionfacts_alter_game_status_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0056_user_home_hide_unreleased'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='game_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='list_detail_status_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='game_status',
            field=models.CharField(choices=[('All', 'All'), ('Planned', 'Planned'), ('Played', 'Played'), ('In progress', 'In Progress'), ('Dropped', 'Dropped')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_detail_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Planned', 'Planned'), ('Played', 'Played'), ('In progress', 'In Progress'), ('Dropped', 'Dropped')], default='All', max_length=20),
        ),
        migrations.RunPython(merge_game_filters),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_status__in', ['All', 'Completed', 'Planning', 'Paused', 'Planned', 'Played', 'In progress', 'Dropped'])), name='list_detail_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('game_status__in', ['All', 'Planned', 'Played', 'In progress', 'Dropped'])), name='game_status_valid'),
        ),
    ]
