# Generated by Django 5.2.16 on 2026-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_owned_status_and_wishlist'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0057_remove_user_game_status_valid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='movie_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='list_detail_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='game_status_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='game_status',
            field=models.CharField(choices=[('Owned', 'Owned'), ('All', 'All'), ('Planned', 'Planned'), ('Played', 'Played'), ('In progress', 'In Progress'), ('Dropped', 'Dropped')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_detail_status',
            field=models.CharField(choices=[('Owned', 'Owned'), ('All', 'All'), ('Completed', 'Completed'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Planned', 'Planned'), ('Played', 'Played'), ('In progress', 'In Progress'), ('Dropped', 'Dropped')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Owned', 'Owned'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_status__in', ['Owned', 'All', 'Completed', 'Planning', 'Paused', 'Planned', 'Played', 'In progress', 'Dropped'])), name='list_detail_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('movie_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Owned', 'Paused', 'Dropped'])), name='movie_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('game_status__in', ['Owned', 'All', 'Planned', 'Played', 'In progress', 'Dropped'])), name='game_status_valid'),
        ),
    ]
