# Generated by Django 5.2.16 on 2026-09-19 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0064_restore_tz_shifted_media_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('steam', 'Steam'), ('itch', 'itch.io')], max_length=16)),
                ('external_id', models.CharField(max_length=32)),
                ('credential', models.TextField(editable=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt', models.DateTimeField(null=True)),
                ('last_success', models.DateTimeField(null=True)),
                ('status', models.CharField(default='Ready to sync', max_length=200)),
                ('generation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('lease', models.UUIDField(editable=False, null=True)),
                ('busy_until', models.DateTimeField(editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('minutes', models.PositiveIntegerField(null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='game_connections.gameconnection')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.item')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddConstraint(
            model_name='gameconnection',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='one_game_connection_per_user_service'),
        ),
        migrations.AddConstraint(
            model_name='gameconnection',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='one_game_account_owner'),
        ),
        migrations.AddConstraint(
            model_name='librarygame',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='unique_connection_game'),
        ),
    ]
