# Generated by Django 5.2.16 on 2026-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconnection',
            name='last_wishlist_success',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gameconnection',
            name='wishlist_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='librarygame',
            name='owned',
            field=models.BooleanField(default=True),
        ),
    ]
